### PR TITLE
Implement the v3/authByEmail workflow

### PR DESCRIPTION
**Pull request by PileOfJunkMail**
Use `node index.js login` to request a login email.

This is rough, but I'm totally unfamiliar with NodeJS, so I'm already
happy that it works.

Note: Check your config file and make sure you don't have an old
User-Agent header defined.

### CODE REVIEW

**Comment by axoroll7** [comment]
(sorry for bad english) I have two questions :

- Firt question : Using your patch, will the "login" command be needed at each startup of the command "watch" ? I am asking this question, because I restart automatically my computer every day. Should I keep my computer powered on for months ?
- Second question : How long does it take for the tokens created by the "login" command to be invalided ? Weeks, months ?

Thank you very much for your work

**Comment by unixfox** [comment]
The tokens are saved in the config.json file so a restart won't require a "login" command.

And for the second question, I think only time will tell. We don't know anything about the toogoodtogo backend because they don't disclose their source code.

**Comment by axoroll7** [comment]
> The tokens are saved in the config.json file so a restart won't require a "login" command.
> 
> And for the second question, I think only time will tell. We don't know anything about the toogoodtogo backend because they don't disclose their source code.

Thank you very much

**Comment by marklagendijk** [comment]
Thanks for the PR! I'll merge it and do some changes to improve it.
Normally it's nicer to do them via review comments, but that is more time intensive, and I don't currently have much time for this.

**Comment by marklagendijk** [comment]
Released as 3.8.0.
I also added functionality for logging in via the Telegram bot.

**Pull request merged**
