### PR TITLE
mqtt integration

### PR DESCRIPTION
**Pull request by a-p-z**

### CODE REVIEW

**Comment by marklagendijk** [comment]
Just to let you know: I'm very interested in this feature.
I'm particularly interested in using this in combination with HomeAssistant.

To me the tricky part is:
* What parts need to be configurable to make it widely applicable?
* Should there be a message per business or per event (which may contain multiple businesses)?
* Does it make sense to publish [HomeAssistant auto discovery](https://www.home-assistant.io/docs/mqtt/discovery/) information, maybe as [sensor](https://www.home-assistant.io/integrations/sensor.mqtt/)?

How are you currently using this?

**Comment by a-p-z** [comment]
Indeed I use it in combination with HomeAssistant!
Telegram integration in node-toogoodtogo-watcher pulls messages and it means you have to use a dedicated bot just for node-toogoodtogo-watcher even if you want just to send messages.
That was an issue because I did not want to create another bot just for this purpose.

To answer to your question:
1. I think it is already widely applicable, you set the mqtt server host, port and a topic and the watcher sends messages (someone else will subscribe to the same topic and will do actions)
2. In my opinion one business per message is better, the subscriber can group them if it needs
3. implementing the autodiscovery is possible but I see it more as a trigger than a sensor, I have to think about it as a sensor. If I have an idea I will write you
4. I currently use it as a trigger in automation to send me messages by telegram (something that the watcher already does but I can have more flexibility)
`- id: '1633558992812'
  alias: '[toogoodtogo] on TooGoodToGo topic → send message'
  description: ''
  trigger:
  - platform: mqtt
    topic: TooGoodToGo
  condition: []
  action:
  - service: notify.antonino
    data:
      title: TooGoodToGo
      message: '{{ trigger.payload_json.name }}{{ "\n" }}{{ trigger.payload_json.pickup}}{{
        "\nQuantity: " }}{{ trigger.payload_json.quantity }}{{ "\n" }} {{ trigger.payload_json.packaging_option
        }}'
      data:
        photo:
        - url: '{{ trigger.payload_json.picture }}'
          caption: '{{ trigger.payload_json.name }}{{ "\n" }}{{ trigger.payload_json.pickup}}{{
            "\nQuantity: " }}{{ trigger.payload_json.quantity }}{{ "\n" }} {{ trigger.payload_json.packaging_option
            }}'
`
I could notify different people according to some condition if they are at work or at home for example, etc

**Comment by marklagendijk** [comment]
I found this repository where someone made something similar in Python.
Maybe we should consider his approach and weigh the pros and cons.
I think this is important because we don't want to change the approach after it has been released.

**Comment by a-p-z** [comment]
which repository?

**Comment by marklagendijk** [comment]
Oops, forgot to insert the link. https://github.com/MaxWinterstein/toogoodtogo-ha-mqtt-bridge

**Comment by a-p-z** [comment]
I had a look, it is a nice project but the purpose is different.
What I had in mind was a generic integration with mqtt, that project is an integration with home-assistant with the auto discovery etc.
Do you prefer something like that?

**Comment by MaxWinterstein** [comment]
Hello 😉 

> What I had in mind was a generic integration with mqtt, that project is an integration with home-assistant with the auto discovery etc.

Auto discovery is just some additional message you send on a specific topic. It informs HomeAssistant on what Topic it should watch for new states/triggers/etc.

IMHO I think you can keep your current version as it is (no mqtt dev here :v:) and just add some property to additionally push messages on the autodiscovery topic, as I do here:

https://github.com/MaxWinterstein/toogoodtogo-ha-mqtt-bridge/blob/badb312eed7fb6b7b583410eb25fcaef46ee6ad5/toogoodtogo_ha_mqtt_bridge/main.py#L40-L54

**Note**: Auto-discovered items are kept until explicitly deleted. Handling of deprecated items (e.g. no longer watched) is a bonus. 

https://github.com/MaxWinterstein/toogoodtogo-ha-mqtt-bridge/blob/badb312eed7fb6b7b583410eb25fcaef46ee6ad5/toogoodtogo_ha_mqtt_bridge/main.py#L145

**Comment by marklagendijk** [comment]
I prefer integrating with Apprise instead of supporting all possible notification systems, see #173.

When we have that we can add documentation / examples for use cases that are trickier (as I expect MQTT will be).

**Pull request closed without merging**
