### PR TITLE
Automatically build+publish for arm/v7 and arm64 (and more if you want)

### PR DESCRIPTION
**Pull request by schklom**
This setup uses GitHub Actions to build an image for arm/v7 and arm64 then publish them on DockerHub (you need to setup repo secrets first) every time you want (workflow_dispatch), every push, every pull requests (pull_requests), and everyday at midnight.
It also checks the dependencies' versions for the Actions everyday and creates a pull request if there are new versions available.

Remove the triggers you don't want :)

Reminder: if you ever move the Dockerfile (or some dependencies), you will have to correct the Dockerfile path (and/or the context path).

### CODE REVIEW

**Comment by marklagendijk** [comment]
@schklom awesome! Thanks!

**Comment by marklagendijk** [comment]
@schklom I'm going to make the approach a bit more generalized, so I can easily use it for my other repos as well. Also I can make pull requests to other repos that are missing multiarch builds.
See [this commit](https://github.com/marklagendijk/node-toogoodtogo-watcher/commit/572c330ca435510f41a50e0117e4076bbae181f6).

I really love that multiarch builds are simple now :). I [requested](https://github.com/docker/hub-feedback/issues/1874) Docker Hub to add support for this a long time ago.

**Comment by marklagendijk** [comment]
@schklom I'm working on making the whole thing dynamic, so I can just copy it to my other similar repositories, and can add pull requests to repos that are missing it.

**Comment by marklagendijk** [comment]
@schklom I managed to get it working! Thanks again for this PR!

**Comment by schklom** [comment]
@marklagendijk My pleasure !
I'm personally using it to fork+sync+build for repos that don't provide an arm image, and since it felt like you wanted to provide images for other platforms I thought it might help ;)

It's a shame that DockerHub doesn't support many though

PS: If you want to automatically build images of foreign repos, I have setup Actions similar to this that do it automatically in my repo :p

**Pull request merged**
