### PR TITLE
Mimic even more the toogoodtogo app

### PR DESCRIPTION
**Pull request by unixfox**
Closes https://github.com/marklagendijk/node-toogoodtogo-watcher/issues/112
Closes https://github.com/marklagendijk/node-toogoodtogo-watcher/issues/113

### CODE REVIEW

**Comment by epandi** [comment]
Verified to solve issues #112 and #113

**Comment by beatbrot** [comment]
Yeah, I also just verified it solves #112 and #113

**Comment by MaxWinterstein** [comment]
But this does not fix the login issue, or am i missing out something?

Tried with newest Docker image and fresh `config.json`, only added username/password.

**Comment by unixfox** [comment]
> But this does not fix the login issue, or am i missing out something?
> 
> Tried with newest Docker image and fresh `config.json`, only added username/password.

I found that toogoodtoogo may ban your IP if you used node-toogoodtogo-watcher before on the same IP, using a fresh new IP solve the issue.

**Pull request merged**
